[build]
publish = "public"
command = "hugo"

[build.environment]
HUGO_VERSION = "0.53"

[context.deploy-preview]
command = "hugo --baseURL $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --baseURL $DEPLOY_PRIME_URL"
